<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:test-suite start="1615460628440" stop="1615460717485" version="1.5.0" xmlns:ns2="urn:model.allure.qatools.yandex.ru">
    <name>Default suite : Default test</name>
    <title>Default suite : Default test</title>
    <test-cases>
        <test-case start="1615460634298" stop="1615460705870" status="failed">
            <name>Login</name>
            <failure>
                <message>AssertionError: [ASSERT FAILED]: Element login_textBox_username not found on the LoginPage !!!</message>
                <stack-trace>java.lang.AssertionError: [ASSERT FAILED]: Element login_textBox_username not found on the LoginPage !!!
	at org.testng.Assert.fail(Assert.java:94)
	at com.qait.automation.getpageobjects.GetPage.element(GetPage.java:146)
	at com.qait.automation.getpageobjects.GetPage.element(GetPage.java:133)
	at com.qait.keywords.LoginPageAction.enterValidCredentials(LoginPageAction.java:47)
	at com.qait.tests.HomepageTest.Login(HomepageTest.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</stack-trace>
            </failure>
            <steps/>
            <attachments/>
            <labels>
                <label name="testSuite" value="Default suite"/>
                <label name="testGroup" value="Default test"/>
                <label name="testClass" value="com.qait.tests.HomepageTest"/>
                <label name="testMethod" value="Login"/>
                <label name="host" value="faizejafri-Vostro-15-3568"/>
                <label name="thread" value="199629@faizejafri-Vostro-15-3568.main(1)"/>
            </labels>
        </test-case>
        <test-case start="1615460634298" stop="1615460705870" status="failed">
            <name>Login</name>
            <failure>
                <message>AssertionError: [ASSERT FAILED]: Element login_textBox_username not found on the LoginPage !!!</message>
                <stack-trace>java.lang.AssertionError: [ASSERT FAILED]: Element login_textBox_username not found on the LoginPage !!!
	at org.testng.Assert.fail(Assert.java:94)
	at com.qait.automation.getpageobjects.GetPage.element(GetPage.java:146)
	at com.qait.automation.getpageobjects.GetPage.element(GetPage.java:133)
	at com.qait.keywords.LoginPageAction.enterValidCredentials(LoginPageAction.java:47)
	at com.qait.tests.HomepageTest.Login(HomepageTest.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</stack-trace>
            </failure>
            <steps/>
            <attachments/>
            <labels>
                <label name="testSuite" value="Default suite"/>
                <label name="testGroup" value="Default test"/>
                <label name="testClass" value="com.qait.tests.HomepageTest"/>
                <label name="testMethod" value="Login"/>
                <label name="host" value="faizejafri-Vostro-15-3568"/>
                <label name="thread" value="199629@faizejafri-Vostro-15-3568.main(1)"/>
            </labels>
        </test-case>
        <test-case start="1615460705885" stop="1615460717483" status="broken">
            <name>verify_SideLinks_are_present</name>
            <failure>
                <message>Test was interrupted</message>
            </failure>
            <labels>
                <label name="testSuite" value="Default suite"/>
                <label name="testGroup" value="Default test"/>
                <label name="testClass" value="com.qait.tests.HomepageTest"/>
                <label name="testMethod" value="verify_SideLinks_are_present"/>
                <label name="host" value="faizejafri-Vostro-15-3568"/>
                <label name="thread" value="199629@faizejafri-Vostro-15-3568.main(1)"/>
            </labels>
        </test-case>
        <test-case start="1615460705885" stop="1615460717483" status="broken">
            <name>verify_SideLinks_are_present</name>
            <failure>
                <message>Test was interrupted</message>
            </failure>
            <labels>
                <label name="testSuite" value="Default suite"/>
                <label name="testGroup" value="Default test"/>
                <label name="testClass" value="com.qait.tests.HomepageTest"/>
                <label name="testMethod" value="verify_SideLinks_are_present"/>
                <label name="host" value="faizejafri-Vostro-15-3568"/>
                <label name="thread" value="199629@faizejafri-Vostro-15-3568.main(1)"/>
            </labels>
        </test-case>
        <test-case start="1615460628440" stop="1615460717483" status="broken">
            <name>Default suite : Default test</name>
            <title>Default suite : Default test</title>
            <failure>
                <message>Test suite was interrupted, some test cases may be lost</message>
            </failure>
        </test-case>
    </test-cases>
    <labels>
        <label name="framework" value="TestNG"/>
        <label name="language" value="JAVA"/>
    </labels>
</ns2:test-suite>
