<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:test-suite start="1616153882947" stop="1616154005075" version="1.5.0" xmlns:ns2="urn:model.allure.qatools.yandex.ru">
    <name>Default suite : Default test</name>
    <title>Default suite : Default test</title>
    <test-cases>
        <test-case start="1616153896062" stop="1616153920656" status="passed">
            <name>Login</name>
            <steps/>
            <attachments/>
            <labels>
                <label name="testSuite" value="Default suite"/>
                <label name="testGroup" value="Default test"/>
                <label name="testClass" value="com.qait.tests.NotificationsTest"/>
                <label name="testMethod" value="Login"/>
                <label name="host" value="faizejafri-Vostro-15-3568"/>
                <label name="thread" value="704739@faizejafri-Vostro-15-3568.main(1)"/>
            </labels>
        </test-case>
        <test-case start="1616153896062" stop="1616153920656" status="passed">
            <name>Login</name>
            <steps/>
            <attachments/>
            <labels>
                <label name="testSuite" value="Default suite"/>
                <label name="testGroup" value="Default test"/>
                <label name="testClass" value="com.qait.tests.NotificationsTest"/>
                <label name="testMethod" value="Login"/>
                <label name="host" value="faizejafri-Vostro-15-3568"/>
                <label name="thread" value="704739@faizejafri-Vostro-15-3568.main(1)"/>
            </labels>
        </test-case>
        <test-case start="1616153920693" stop="1616154005011" status="failed">
            <name>verify_Newly_Notification_Sent_isDisplayed_on_Homepage_and_at_StudentEnd</name>
            <failure>
                <message>AssertionError: [ASSERT FAILED]: Element btn_Continue not found on the Notifications !!!</message>
                <stack-trace>java.lang.AssertionError: [ASSERT FAILED]: Element btn_Continue not found on the Notifications !!!
	at org.testng.Assert.fail(Assert.java:94)
	at com.qait.automation.getpageobjects.GetPage.element(GetPage.java:146)
	at com.qait.automation.getpageobjects.GetPage.element(GetPage.java:133)
	at com.qait.keywords.NotificationAction.Login_Using_Student_Credentials(NotificationAction.java:299)
	at com.qait.tests.NotificationsTest.verify_Newly_Notification_Sent_isDisplayed_on_Homepage_and_at_StudentEnd(NotificationsTest.java:210)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</stack-trace>
            </failure>
            <steps/>
            <attachments/>
            <labels>
                <label name="testSuite" value="Default suite"/>
                <label name="testGroup" value="Default test"/>
                <label name="testClass" value="com.qait.tests.NotificationsTest"/>
                <label name="testMethod" value="verify_Newly_Notification_Sent_isDisplayed_on_Homepage_and_at_StudentEnd"/>
                <label name="host" value="faizejafri-Vostro-15-3568"/>
                <label name="thread" value="704739@faizejafri-Vostro-15-3568.main(1)"/>
            </labels>
        </test-case>
        <test-case start="1616153920693" stop="1616154005011" status="failed">
            <name>verify_Newly_Notification_Sent_isDisplayed_on_Homepage_and_at_StudentEnd</name>
            <failure>
                <message>AssertionError: [ASSERT FAILED]: Element btn_Continue not found on the Notifications !!!</message>
                <stack-trace>java.lang.AssertionError: [ASSERT FAILED]: Element btn_Continue not found on the Notifications !!!
	at org.testng.Assert.fail(Assert.java:94)
	at com.qait.automation.getpageobjects.GetPage.element(GetPage.java:146)
	at com.qait.automation.getpageobjects.GetPage.element(GetPage.java:133)
	at com.qait.keywords.NotificationAction.Login_Using_Student_Credentials(NotificationAction.java:299)
	at com.qait.tests.NotificationsTest.verify_Newly_Notification_Sent_isDisplayed_on_Homepage_and_at_StudentEnd(NotificationsTest.java:210)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</stack-trace>
            </failure>
            <steps/>
            <attachments/>
            <labels>
                <label name="testSuite" value="Default suite"/>
                <label name="testGroup" value="Default test"/>
                <label name="testClass" value="com.qait.tests.NotificationsTest"/>
                <label name="testMethod" value="verify_Newly_Notification_Sent_isDisplayed_on_Homepage_and_at_StudentEnd"/>
                <label name="host" value="faizejafri-Vostro-15-3568"/>
                <label name="thread" value="704739@faizejafri-Vostro-15-3568.main(1)"/>
            </labels>
        </test-case>
    </test-cases>
    <labels>
        <label name="framework" value="TestNG"/>
        <label name="language" value="JAVA"/>
    </labels>
</ns2:test-suite>
